#!/usr/bin/env sh
### Common section Begin
set -u  # Treat unset variables as an error.
start_time=$(date +%s)

SCRIPT_DIR="$(dirname "$0")"
LIB_DIR="${SCRIPT_DIR}/php-dev-helper-lib"
MODULES_DIR="${LIB_DIR}/sh-modules"
WORK_DIR="${PWD}"

### LOAD MODULES
# shellcheck disable=SC1090
. "${MODULES_DIR}/include_core.sh"  # Core modules loader
# shellcheck disable=SC1090
. "${LIB_DIR}/include_common.sh"    # Common modules loader

SCRIPT_VERSION="$(version_load_version "${VERSION_FILE}")"
SCRIPT_BUILD="$(version_load_build "${BUILD_FILE}")"

export SCRIPT_VERSION
export SCRIPT_BUILD

__TITLE="$(core_get_title_from_file "${WORK_DIR}/TERMINAL_TITLE" "${WORK_DIR}")"

### Common section End
### Script Code
# shellcheck disable=SC1090
. "${LIB_DIR}/include_bdi.sh"       # Moomba modules loader

### Read options
bdi_load_settings
bdi_read_options "$@"

func_print_header "Docker image build tool"

### Run checks
bdi_show_settings
bdi_check_working_env

### Building image
if [ "${COMMON_EXECUTE:-${CR_TRUE}}" -eq "${CR_TRUE}" ]; then
    console_warning "Under development - use with caution!"
    core_set_terminal_title "${__TITLE} - Building..."
    console_debug "Executing..."
    console_dark "Building image"
    console_error "It does NOTHING"
else
    console_debug "No execution selected"
fi

func_print_footer "${start_time}"
