#!/usr/bin/env sh
# shellcheck disable=SC1091
. pdh_lib_loader

### Image builder modules loader
# shellcheck disable=SC1090
. "${LIB_DIR}/include_bdi.sh"       

func_print_header "Docker image build tool"

### Run checks
bdi_show_settings
bdi_check_working_env

### Building image
if [ "${COMMON_EXECUTE:-${CR_TRUE}}" -eq "${CR_TRUE}" ]; then
    console_warning "Under development - use with caution!"
    core_set_terminal_title "${__TITLE} - Building..."
    console_debug "Executing..."
    console_dark "Building image"
    console_error "It does NOTHING"
else
    console_debug "No execution selected"
fi

func_print_footer
