#!/usr/bin/env sh

# Disable source following.
#   shellcheck disable=SC1090,SC1091

. ./php-dev-helper_loader

### Install modules loader
. "${INCLUDERS_DIR}/include_install.sh"      

install_load_settings
install_read_options "$@"

func_print_header "PHP Dev Helper Installer" 

### Installing suite
if [ "${COMMON_EXECUTE:-${CR_TRUE}}" -eq "${CR_TRUE}" ]; then
    console_warning "Under development - work in progress!"
    install_get_destination 
    if core_ask_question "Install PHP Dev Helper to '${SUITE_DIR}'?"; then
        install_copy_files_to_destination
        install_rename_scripts
        install_cleanup
        export FLAG_DONE="${CR_TRUE}"
    else
        export FLAG_CANCELED="${CR_TRUE}"
    fi
else
    console_debug "No execution selected"
fi

func_print_footer
