#!/usr/bin/env sh

# shellcheck disable=SC1091
. pdh_lib_loader

### Moomba modules loader
# shellcheck disable=SC1090
. "${INCLUDERS_DIR}/include_mmb.sh"      

mmb_load_settings
mmb_read_options "$@"

func_print_header "PHP Package creator"

mmb_show_settings
mmb_check_working_env

### Creating new package
if [ "${COMMON_EXECUTE:-${CR_TRUE}}" -eq "${CR_TRUE}" ]; then
    console_warning "Under development - use with caution!"
    mmb_working_dir
    mmb_check_default_template
    core_set_terminal_title "${__TITLE} - Creating..."
    console_debug "Executing..."
    console_dark "Creating new package"
    mmb_show_package_values
    if core_ask_question "Create package '${TMPL_PACKAGE_DIR}'?"; then
        mmb_check_package_dir "${TMPL_PACKAGE_DIR}"
        mmb_create_package "${TMPL_USE_TEMPLATE_NAME}" "${TMPL_PACKAGE_DIR}"
        mmb_package_created "${TMPL_PACKAGE_DIR}"
        export FLAG_DONE="${CR_TRUE}"
    else
        export FLAG_CANCELED="${CR_TRUE}"
    fi
    mmb_cleanup
else
    console_debug "No execution selected"
fi

func_print_footer
