#!/usr/bin/env sh

# Disable source following.
#   shellcheck disable=SC1090,SC1091

. php-dev-helper_loader

### Moomba modules loader
. "${INCLUDERS_DIR}/include_mmb.sh"      

mmb_load_settings
mmb_check_working_env
mmb_read_options "$@"

func_print_header "PHP Package creator"

### Creating new package
if [ "${COMMON_EXECUTE:-${CR_TRUE}}" -eq "${CR_TRUE}" ]; then
    console_warning "Under development - use with caution!"
    mmb_working_dir
    mmb_check_default_template
    core_set_terminal_title "${TERM_TITLE} - Creating..."
    mmb_show_package_values
    console_dark "Creating new package"
    if core_ask_question "Create package '${TMPL_PACKAGE_DIR}'?"; then
        mmb_check_package_dir "${TMPL_PACKAGE_DIR}"
        mmb_create_package "${TMPL_WORKING_TEMPLATE_NAME}" "${TMPL_PACKAGE_DIR}"
        mmb_package_created "${TMPL_PACKAGE_DIR}"
        export FLAG_DONE="${CR_TRUE}"
    else
        export FLAG_CANCELED="${CR_TRUE}"
    fi
    mmb_cleanup
else
    console_debug "No execution selected"
fi

func_print_footer
