#!/usr/bin/env sh
set -u  # Treat unset variables as an error.

SCRIPT_NAME="$(basename "$0")"
SCRIPT_DIR="$(dirname "$0")"
LIB_DIR="${SCRIPT_DIR}/lib"
COMMANDS_DIR="${LIB_DIR}/commands"
WORK_DIR="${PWD}"

# shellcheck disable=SC1090
. "${LIB_DIR}/core.sh"
# shellcheck disable=SC1090
. "${LIB_DIR}/logging.sh"
# shellcheck disable=SC1090
. "${LIB_DIR}/version.sh"
# shellcheck disable=SC1090
. "${LIB_DIR}/options.sh"
# shellcheck disable=SC1090
. "${LIB_DIR}/helpers.sh"
# shellcheck disable=SC1090
. "${LIB_DIR}/settings.sh"
# shellcheck disable=SC1090
. "${COMMANDS_DIR}/phpunit.sh"

_read_options "$@"

### Print header
_log_header "PHP tests script"
_log_debug "Version $(_version)"

### Start
__TITLE="$(_pts_get_title_from_file "${WORK_DIR}/TERMINAL_TITLE" "${WORK_DIR}")"
__title="${__TITLE} - Testing..."
_log_debug "Setting title '${__title}'"
_pts_set_terminal_title "${__title}"

_show_options
PTS_CONTAINER_STARTED="$(_is_container_started)"
_is_debug_image_used
# if _is_container_started 
# then
#     _is_debug_image_used
# fi

if [ "${PTS_EXECUTE}" -eq "${PTS_TRUE}" ] 
then
    _log_debug "Executing..."
fi
# _phpunit_exec

### Finish
__title="${__TITLE}"
_log_debug "Setting title '${__title}'"
_pts_set_terminal_title "${__title}"

### Debug code 
_log_debug "Debug messages:"
_log_debug "SCRIPT_NAME: ${SCRIPT_NAME}"
_log_debug "SCRIPT_DIR: ${SCRIPT_DIR}"
_log_debug "WORK_DIR: ${WORK_DIR}"

_log_dark "dark"
_log_info "info"
_log_comment "comment"
_log_notice "notice"

_log_warn "Warn message"
_log_error "Error message"
_log_fatal "Fatal message"