#!/usr/bin/env sh

# shellcheck disable=SC1091
. pdh_lib_loader

### Php-tests modules loader
# shellcheck disable=SC1090
. "${LIB_DIR}/include_pts.sh"       

func_print_header "PHP Tests and Analysis tool"

### Run checks
_pts_check_working_env
_pts_show_project_type_and_name

console_debug "Output use color: $(core_int_to_string "${CR_COLOR}")"

_pts_show_selected_options
_pts_check_container
_pts_check_vendor_dir

### Testing
if [ "${COMMON_EXECUTE}" -eq "${CR_TRUE}" ]; then
    core_set_terminal_title "${__TITLE} - Testing..."
    console_debug "Executing..."
    if [ "${PTS_CONTAINER_STARTED}" -eq "${CR_TRUE}" ]; then
        console_comment "${EMOJI_ROCKET}Processing...."
        _phpunit_exec
        _var_dump_check_exec
        _php_metrics_exec
        _multi_tester_exec
        _phpstan_exec
        _psalm_exec
        _php_security_exec
        _php_cs_exec
        _php_cs_bf_exec
        _php_dependency_graph

        if [ "${PTS_METRICS}" -eq "${CR_TRUE}" ] \
        || [ "${PTS_PHPUNIT_COVERAGE}" -eq "${CR_TRUE}" ] \
        || [ "${PTS_DEPS_GRAPH}" -eq "${CR_TRUE}" ] \
        ; then
            if [ -e "${PTS_TEST_REPORT_INDEX}" ]
            then
                console_print ""
                console_debug "Report file found: '${PTS_TEST_REPORT_INDEX}'"
            else
                console_comment "Generating report file: '${PTS_TEST_REPORT_INDEX}'"
                _pts_generate_report_file
            fi
        fi
    else
        console_error "Container is not started"
    fi
fi

func_print_footer
