#!/usr/bin/env sh
set -u  # Treat unset variables as an error.
start_time=$(date +%s)

SCRIPT_NAME="$(basename "$0")"
export SCRIPT_NAME

SCRIPT_DIR="$(dirname "$0")"
MODULES_DIR="${SCRIPT_DIR}/sh-modules"
LIB_DIR="${SCRIPT_DIR}/php-dev-helper-lib"
WORK_DIR="${PWD}"

# shellcheck disable=SC1090
. "${MODULES_DIR}/core.sh"
# shellcheck disable=SC1090
. "${MODULES_DIR}/github.sh"
# shellcheck disable=SC1090
. "${MODULES_DIR}/docker.sh"
# shellcheck disable=SC1090
. "${MODULES_DIR}/git.sh"
# shellcheck disable=SC1090
. "${MODULES_DIR}/version.sh"
# shellcheck disable=SC1090
. "${MODULES_DIR}/updater.sh"
# shellcheck disable=SC1090
. "${LIB_DIR}/options.sh"
# shellcheck disable=SC1090
. "${LIB_DIR}/functions.sh"
# shellcheck disable=SC1090
. "${LIB_DIR}/commands.sh"
# shellcheck disable=SC1090
. "${LIB_DIR}/settings.sh"
# Load PTS_AUX_DEV_MODULE module if present
if [ -e "${LIB_DIR}/${PTS_AUX_DEV_MODULE}" ]; then
    # shellcheck disable=SC1090
    . "${LIB_DIR}/${PTS_AUX_DEV_MODULE}" && console_debug "Module '${PTS_AUX_DEV_MODULE}' processed"
else
    console_debug "Aux dev module '${PTS_AUX_DEV_MODULE}' not found"
fi

SCRIPT_VERSION="$(version_load_version "${VERSION_FILE}")"
SCRIPT_BUILD="$(version_load_build "${BUILD_FILE}")"

export SCRIPT_VERSION
export SCRIPT_BUILD

### Read options
_pts_read_options "$@"

__TITLE="$(core_get_title_from_file "${WORK_DIR}/TERMINAL_TITLE" "${WORK_DIR}")"

func_print_header "PHP Tests and Analysis tool"

### Run checks
_pts_check_working_env
_pts_show_selected_options
_pts_check_container


### Testing
if [ "${PTS_EXECUTE}" -eq "${CR_TRUE}" ]; then
    core_set_terminal_title "${__TITLE} - Testing..."
    console_debug "Executing..."
    if [ "${PTS_CONTAINER_STARTED}" -eq "${CR_TRUE}" ]; then
        console_comment "${EMOJI_ROCKET}Processing...."
        _phpunit_exec
        _php_metrics_exec
        _multi_tester_exec
        _phpstan_exec
        _psalm_exec
        _php_cs_exec
        _php_cs_bf_exec

        if [ -e "${PTS_TEST_REPORT_INDEX}" ]
        then
            console_info "Report file found: '${PTS_TEST_REPORT_INDEX}'"
        else
            console_comment "Generating report file: '${PTS_TEST_REPORT_INDEX}'"
            _pts_generate_report_file
        fi
        console_print ""
    else
        console_error "Container is not started"
    fi
fi

func_print_footer "${start_time}"
