#!/usr/bin/env sh

# Disable source following.
#   shellcheck disable=SC1090,SC1091

command [ -n "${MODULE_LOADED:-}" ] && exit 0
MODULE_LOADED="LOADED"

# Directories
__lib="php-dev-helper"
__core_modules="core"
__common_modules="common"
__apps_modules="apps"
__includers="includers"

# Treat unset variables as an error.
set -u

# Set core variables
SCRIPT_DIR=${SCRIPT_DIR:-"$(dirname "$0")"}
LIB_DIR="${SCRIPT_DIR}/${__lib}"
COMMON_MODULES_DIR="${LIB_DIR}/${__common_modules}"
CORE_MODULES_DIR="${LIB_DIR}/${__core_modules}"
APPS_MODULES_DIR="${LIB_DIR}/${__apps_modules}"
INCLUDERS_DIR="${LIB_DIR}/${__includers}"
WORK_DIR="${PWD}"

# Source modules
. "${INCLUDERS_DIR}/include_core.sh"      # Core modules loader
. "${INCLUDERS_DIR}/include_common.sh"    # Common modules loader

SCRIPT_VERSION="$(version_load_version "${VERSION_FILE}")"
SCRIPT_BUILD="$(version_load_build "${BUILD_FILE}")"

console_debug "Modules loaded"

# TODO rename var to TERM_TITLE
TERM_TITLE="$(core_get_title_from_file "${WORK_DIR}/TERMINAL_TITLE" "${WORK_DIR}")"

export SCRIPT_VERSION
export SCRIPT_BUILD
export COMMON_MODULES_DIR
export CORE_MODULES_DIR
export APPS_MODULES_DIR
export INCLUDERS_DIR
export TERM_TITLE

console_debug "Loader - Done"

unset __lib __core_modules __common_modules __apps_modules __includers
