#!/usr/bin/env sh
set -u  # Treat unset variables as an error.

SCRIPT_NAME="$(basename "$0")"
SCRIPT_DIR="$(dirname "$0")"
LIB_DIR="${SCRIPT_DIR}/lib"
WORK_DIR="${PWD}"

# shellcheck disable=SC1090
. "${LIB_DIR}/core.sh"
# shellcheck disable=SC1090
. "${LIB_DIR}/logging.sh"
# shellcheck disable=SC1090
. "${LIB_DIR}/version.sh"
# shellcheck disable=SC1090
. "${LIB_DIR}/options.sh"

_read_options "$@"

### Print header
_log_header "PHP tests script"
_log_debug "Version $(_version)"

### Debug code 
_log_debug "SCRIPT_NAME: ${SCRIPT_NAME}"
_log_debug "SCRIPT_DIR: ${SCRIPT_DIR}"
_log_debug "WORK_DIR: ${WORK_DIR}"

_log_dark "dark"
_log_info "info"
_log_comment "comment"
_log_notice "notice"

_log_warn "Warn message"
_log_error "Error message"
_log_fatal "Fatal message"